FROM httpd:2.4
MAINTAINER username

RUN apt-get update

#COPY httpd.conf /usr/local/apache2/conf/
#COPY httpd-vhosts.conf /usr/local/apache2/conf/extra/
#COPY httpd-ssl.conf /usr/local/apache2/conf/extra/
#COPY server.csr /usr/local/apache2/conf/
#COPY server.crt /usr/local/apache2/conf/
#COPY server.key /usr/local/apache2/conf/
